name: campusdashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.4.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bzip2=1.0
  - ca-certificates=2023.7.
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - expat=2.5.0
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - libcxx=14.0.6
  - libexpat=2.5.0
  - libffi=3.4.4
  - libsodium=1.0.18
  - libsqlite=3.44.0
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.1.4
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3
  - platformdirs=4.0.0
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.16.1
  - python=3.12.0
  - python-dateutil=2.8.2
  - python_abi=3.12
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.13.0
  - typing_extensions=4.8.0
  - wcwidth=0.2.10
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - altair==5.1.2
      - anyio==4.0.0
      - attrs==23.1.0
      - blinker==1.7.0
      - cachetools==5.3.2
      - certifi==2023.7.22
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - et-xmlfile==1.1.0
      - fastjsonschema==2.19.0
      - filelock==3.13.1
      - fonttools==4.44.3
      - gitdb==4.0.11
      - gitpython==3.1.40
      - h11==0.14.0
      - humanize==4.8.0
      - idna==3.4
      - ipyvue==1.10.1
      - ipyvuetify==1.8.10
      - ipywidgets==8.1.1
      - jinja2==3.1.2
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.11.1
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.1
      - mdurl==0.1.2
      - nbformat==5.9.2
      - numpy==1.26.2
      - openpyxl==3.1.2
      - pandas==2.1.3
      - pillow==10.1.0
      - plotly==5.18.0
      - protobuf==4.25.1
      - pyarrow==14.0.1
      - pydeck==0.8.1b0
      - pymdown-extensions==10.4
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - reacton==1.8.0
      - referencing==0.31.0
      - requests==2.31.0
      - rich==13.7.0
      - rich-click==1.7.1
      - rpds-py==0.12.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - solara==1.22.0
      - starlette==0.32.0.post1
      - streamlit==1.28.2
      - tenacity==8.2.3
      - toml==0.10.2
      - toolz==0.12.0
      - tzdata==2023.3
      - tzlocal==5.2
      - urllib3==2.1.0
      - uvicorn==0.24.0.post1
      - validators==0.22.0
      - watchdog==3.0.0
      - websockets==12.0
      - widgetsnbextension==4.0.9
# prefix: /Users/anupamsobti/anaconda3/envs/campusdashboard
